### ISSUE TITLE
Modificación de layout

### ISSUE THREAD

**Issue by BaezCrdrm** [BaezCrdrm/RegistrosDCI#9]
Modificación de los layouts de detalle a fin de que cuenten con los valores `ID` disponibles de manera oculta, para que puedan ser utilizados por Java.

**Comment by BaezCrdrm** [comment]
@ark150 Puedes checar esto?

**Comment by ark150** [comment]
si este erro te cerraba la app ya lo corregi y corre en mi cel sin error en un momento hago el push request para qu etengas mis cambios
